### PR TITLE
Upgrade arrow to 53 and other crates

### PR DESCRIPTION
**Pull request by xmakro**
Also increments the major version to 0.10. Please release a new crate as this is a breaking API change

### CODE REVIEW

**Comment by xmakro** [comment]
@dmzmk do you still have admin on this repo to merge the PR?

**Review by dmzmk — APPROVED** [review]

**Comment by dmzmk** [comment]
@xmakro I do now! thanks for contribution

**Comment by dmzmk** [comment]
@xmakro new crate version published

**Comment by xmakro** [comment]
Thanks!

**Pull request merged**
