### PR TITLE
Upgrade crates and new version

### PR DESCRIPTION
**Pull request by xmakro**
Please release as follows:
1. Publish `snowflake-jwt` version `0.3.1`
1. Publish `snowflake-api` version `0.8`

### CODE REVIEW

**Review by dmzmk — APPROVED** [review]

**Comment by xmakro** [comment]
Updated reqwest to `0.12` as well, so now all crates are up to date. 

I also changed the version increase of snowflake-jwt to be a minor update. jsonwebtoken is only exposed in the Error part of the public api, so a version change is unlikely to break someone and the rollout here becomes slightly easier.

**Comment by sgrebnov** [comment]
@dmzmk, @xmakro - looking forward to `snowflake-api` 0.8.0 release with arrow 51.0.0 support. Thank you!

**Comment by dmzmk** [comment]
@xmakro @sgrebnov new crate versions available on crates.io

**Comment by sgrebnov** [comment]
Thank you @dmzmk - tested new version, works well 🚀. Thank you!

**Pull request merged**
